name: Deploy v2
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v1
        with: 
          node-version: 10.x
      - name: Install Packages and Build Application
        run: |
          npm install
          npm run build
      - name: Add custom domain
        run: |
          cd dist
          echo 'climat-energie-idf.fr' > CNAME

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}