name: Run python scripts

on: 
  push:
    branches: master
    paths: 'python_scripts/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7  #currently on python 2, need to migrate to 3 ASAP
      uses: actions/setup-python@v2
      with:
        python-version: 2.7 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Test python and pip version
      run: python -c "import sys; print(sys.version)"
    # - name: Execute python scripts
    #   run: |
    #     python python_scripts/DRIEE-TDB-traitement/*/*.py
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest