name: Run python scripts

on: 
  push:
    branches: master
    paths: 'python_scripts/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7  #currently on python 2, need to migrate to 3 ASAP
      uses: actions/setup-python@v2
      with:
        python-version: 2.7 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
    - name: Test python and pip version
      run: python -c "import sys; print(sys.version)"
    - name: Execute python script 1
      working-directory: python_scripts/DRIEE-TDB-traitement/Page1_consommation
      run: |
        python traitement_conso_EPCI.py
    - name: Execute python script 2
      working-directory: python_scripts/DRIEE-TDB-traitement/page2_emission
      run: |
        python traitement_epci_emission.py
    - name: Execute python script 3
      working-directory: python_scripts/DRIEE-TDB-traitement/page7_production
      run: |
        python traitement_epci_prod.py
    - name: Setup git config
      run: |
        git config user.name "SECV-PEE"
        git config user.email "crcae.idf@gmail.com"

    - name: Push changes
      working-directory: ./
      run: |
        git add .
        git commit -m "add files from python scripts"
        git push origin master
