name: Test 🔧
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Create Node Environment
        uses: actions/setup-node@v2
        with: 
          node-version: '12'
      - name: Install Packages and Build Application
        run: npm install
      - name: Run server
        run: npm run serve